# Generated by Django 5.2 on 2025-12-18 07:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Train",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "number",
                    models.CharField(max_length=10, unique=True, verbose_name="车次"),
                ),
                (
                    "train_type",
                    models.CharField(
                        choices=[("G", "高铁"), ("D", "动车"), ("T", "特快")],
                        max_length=10,
                        verbose_name="类型",
                    ),
                ),
                ("qi", models.CharField(max_length=50, verbose_name="出发地")),
                ("mudi", models.CharField(max_length=50, verbose_name="目的地")),
                ("start_time", models.DateTimeField(verbose_name="出发时间")),
                ("end_time", models.DateTimeField(verbose_name="到达时间")),
            ],
        ),
        migrations.CreateModel(
            name="Seat",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "seat_type",
                    models.CharField(
                        choices=[
                            ("business", "商务座"),
                            ("first", "一等座"),
                            ("second", "二等座"),
                        ],
                        max_length=20,
                        verbose_name="座位类型",
                    ),
                ),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2, max_digits=7, verbose_name="价格"
                    ),
                ),
                (
                    "number",
                    models.PositiveIntegerField(default=100, verbose_name="剩余票数"),
                ),
                (
                    "train",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="seats",
                        to="ticket.train",
                    ),
                ),
            ],
        ),
    ]
