# Generated by Django 5.2 on 2026-01-05 07:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("my", "0001_initial"),
    ]

    operations = [
        migrations.DeleteModel(name="UserInfo",),
    ]
