# Generated by Django 5.2 on 2025-12-19 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("ticket", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="seat", old_name="seat_type", new_name="type",
        ),
        migrations.AlterField(
            model_name="train",
            name="train_type",
            field=models.CharField(
                choices=[("G", "高铁"), ("D", "动车"), ("T", "特快")],
                max_length=1,
                verbose_name="类型",
            ),
        ),
    ]
